---

homebrew_packages:
  - boost
  - caskroom/cask/brew-cask
  - cowsay
  - docker
  - docker-machine
  - gettext
  - go
  - hg
  - hub
  - ios-sim
  - libevent
  - openssl
  - pkg-config
  - pv
  - python
  - python3
  - readline
  - ssh-copy-id
  - tmux
  - wget
  - zsh

homebrew_python_packages:
  - libjpeg
  - libtiff
  - little-cms2
  - webp
