---

- name: Install Homebrew System Packages
  homebrew:
    name={{ item }}
    state=present
  with_items: homebrew_packages
  tags: ["packages", "system"]

- name: Install Homebrew Python Packages
  homebrew:
    name={{ item }}
    state=present
  with_items: homebrew_python_packages
  tags: ["packages", "python"]
