---

# cf, https://java.com/en/download/help/mac_uninstall_java.xml
- name: java | Uninstall | Uninstall Oracle Java
  file:
    path: "{{ item }}"
    state: absent
  become: yes
  tags: ["security", "java"]
  with_items:
    - "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin"
    - "/Library/PreferencePanes/JavaControlPanel.prefPane"
    - "{{ home }}/Library/Application Support/Oracle/Java"

# cf, https://www.java.com/en/download/help/deployment_cache.xml
- name: java | Uninstall | Remove Oracle Java cache
  file:
    path: "{{ home }}/Library/Application Support/Oracle/Java"
    state: absent
  become: yes
  tags: ["security", "java"]
