---

- name: Install Apps From Homebrew (Cask)
  homebrew_cask: 
    name={{ item }}
    state=present
  with_items: homebrew_cask_apps
  tags: packages

- name: Configure Sublime User Preferences
  template: 
    src="sublime.j2"
    dest={{ sublime_path }}/Preferences.sublime-settings

- name: Configure Sublime Python Preferences
  template:
    src="python-sublime.j2"
    dest={{ sublime_path }}/Python.sublime-settings
