---

- name: Homebrew Cask | Install | Install Homebrew Cask Apps
  homebrew_cask:
    name="{{ item }}"
    state=present
  with_items: "{{ homebrew_cask_apps }}"
  tags: applications

# Install and configure ITerm2
- include: iterm.yml

# Configure firefox profile
- include: firefox.yml
