---

- name: Install Apps From Homebrew (Cask)
  homebrew_cask:
    name={{ item }}
    state=present
  with_items: homebrew_cask_apps
  tags: applications

- name: Configure Sublime User Preferences
  copy:
    src="Preferences.sublime-settings"
    dest="{{ sublime_path }}/Preferences.sublime-settings"
    user={{ user }}

- name: Configure Sublime Python Preferences
  copy:
    src="Python.sublime-settings"
    dest="{{ sublime_path }}/Python.sublime-settings"
    user={{ user }}
