---

- name: Set Global Git Username
  shell: "git config --global user.name '{{ github_username }}'"

- name: Set Global Git Email
  shell: "git config --global user.email '{{ github_email}}'"

- name: Download the latest Playbook Version
  git:
    repo: "{{ git_repo }}"
    dest: "{{ playbook_path }}"
    force: yes
    update: yes
    accept_hostkey: yes
    version: "master"
