---

- name: Homebrew | Configure | Permissions
  file:
    path="/usr/local"
    state=directory
    owner="{{ user }}"
    group="{{ group }}"
  become: yes  # run with sudo in case we need to re-own /usr/local
  tags: ["homebrew"]

- name: Homebrew | Configure | Taps
  homebrew_tap:
    tap="{{ item }}"
    state=present
  with_items: "{{ homebrew_taps }}"
  tags: ["packages", "homebrew"]

- name: Homebrew | Update Homebrew
  homebrew:
    update_homebrew=yes
  tags: ["packages", "homebrew"]

- name: Homebrew | Upgrade Installed Packages
  homebrew:
    upgrade_all=yes
  tags: ["packages", "homebrew"]

- name: Homebrew | Link Installed Packages
  command: brew linkapps
  tags: ["packages", "homebrew"]
