---

- name: Homebrew | Configure Taps
  homebrew_tap:
    tap={{ item }}
    state=present
  with_items: homebrew_taps
  tags: ["packages", "homebrew"]

- name: Homebrew | Update Homebrew
  homebrew:
    update_homebrew=yes
  tags: ["packages", "homebrew"]

- name: Homebrew | Upgrade Installed Packages
  homebrew:
    upgrade_all=yes
  tags: ["packages", "homebrew"]

- name: Homebrew | Link Installed Packages
  command: brew linkapps
  tags: ["packages", "homebrew"]
