---

- name: Python | Install | Python 3.x.x
  homebrew:
    name=python3
    state=present
  tags: ["system", "python"]

- name: Python | Link | Python 3.x.x
  command: brew linkapps python3
  tags: ["system", "python"]

- name: Python | Configure | Create .pypirc
  template:
    src=pypirc.j2
    dest="{{ home }}/.pypirc"
    owner="{{ user }}"
    group="{{ group }}"
    mode=0600
  tags: ["system", "python"]
