---

homebrew_taps:
  - caskroom/cask
  - caskroom/versions
  - homebrew/binary
  - homebrew/cask-fonts

###
### Github Vars
###
github_username: moogar0880
github_email: moogar0880@gmail.com
# git_repo: ssh://git@github.com/moogar0880/osx_provision.git
git_repo: https://github.com/moogar0880/osx_provision.git

# The path to checkout the latest version of this playbook to
playbook_path: "{{ home }}/.deploy"

# The hourly cronjob to run
cron_job: "ansible-playbook -i {{ playbook_path }}/inventory {{ playbook_path }}/local.yml --connection=local"

###
### Python Variables
###
pypi_username: moogar0880

font_casks:
  - font-source-code-pro-for-powerline
  - font-menlo-for-powerline
