---

- name: ZSH | Install | Install ZSH
  homebrew:
    name=zsh
    state=present
  tags: ["packages", "zsh"]

- name: ZSH | Install | Check if oh-my-zsh is Installed
  stat: path="{{ home }}/.oh-my-zsh"
  register: ohmyzsh_conf
  tags: ["zsh", "settings", "oh-my-zsh"]

- name: ZSH | Install | Ensure oh-my-zsh is Installed
  command: "sh -c '$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)'"
  when: ohmyzsh_conf.stat.exists == False
  tags: ["zsh", "settings", "oh-my-zsh"]

- name: ZSH | Configure | Ensure oh-my-zsh Custom Themes Directory Exists
  file:
    path="{{ home }}/.oh-my-zsh/custom/themes/"
    state=directory
    owner="{{ user }}"
    group="{{ group }}"
  tags: ["zsh", "settings", "oh-my-zsh"]

- name: ZSH | Configure | Put Custom Themes in Place
  copy:
    src="{{ item }}.zsh-theme"
    dest="{{ home }}/.oh-my-zsh/custom/themes/{{ item }}.zsh-theme"
    owner="{{ user }}"
    group="{{ group }}"
  with_items:
  - jnappi
  - hyperzsh
  tags: ["zsh", "settings", "oh-my-zsh"]

- name: ZSH | Configure | Setup .zshrc
  template:
    src=zshrc.j2
    dest="{{ home }}/.zshrc"
    owner="{{ user }}"
    group="{{ group }}"
    mode=0600
  tags: ["zsh", "settings", "oh-my-zsh"]
