---

- name: Check if oh-my-zsh is Installed
  stat: path={{ home }}.oh-my-zsh
  register: ohmyzsh_conf

- name: Ensure oh-my-zsh is Installed
  command: "curl -L http://install.ohmyz.sh | sh"
  when: ohmyzsh_conf.stat.exists == False

- name: Put Custom Theme in Place
  copy: 
    src=jnappi.zsh-theme
    dest={{ home }}.oh-my-zsh/custom/themes/jnappi.zsh-theme
    owner={{ user }}
    group=staff

- name: Setup .zshrc
  template: 
    src=zshrc.j2 
    dest=~/.zshrc
    owner={{ user }} 
    group=staff 
    mode=0644

- name: Set ZSH as Default Shell
  command: "chsh -s /bin/zsh {{ user }}"

